name: Todo Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        working-directory: server
        run: go mod download

      - name: Run Tests
        working-directory: server
        run: go test -v ./...

      - name: Run Staticcheck\
        uses: dominikh/staticcheck-action@v1.3.0
        working-directory: server
        with:
          version: 2022.1.3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        working-directory: server
        with:
          version: v1.42.0

      - name: Run gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        working-directory: server
        with:
          gofmt-path: ./
          gofmt-flags: -l -d
